### ISSUE TITLE
Tutorial not working due to ValueError

### ISSUE THREAD

**Issue by Bene94** [entity-neural-network/entity-gym#13]
When trying to reproduce the tutorial, the following error appears:

_Exception has occurred: ValueError
invalid literal for int() with base 10: ''
  File "/local/home/bewinter/entity-gym/treasure_hunt.py", line 82, in <module>
    CliRunner(env).run()
ValueError: invalid literal for int() with base 10: ''_

The code is copied and pasted from tutorial.py. Entity-Gym version is:

 entity-gym                0.1.8                    pypi_0    pypi

**Comment by cswinter** [comment]
This happens when "Enter" is still pressed after the program starts.
Fixed by https://github.com/entity-neural-network/entity-gym/pull/14
