### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by Bene94** [entity-neural-network/entity-gym#15]
**In the complex action space tutorial, the link to the minesweeper example is broken:**

**Is:**

https://github.com/entity-neural-network/incubator/blob/main/entity_gym/entity_gym/examples/minesweeper.py

**Should be:**

https://github.com/entity-neural-network/entity-gym/blob/main/entity_gym/examples/minesweeper.py

**Comment by cswinter** [comment]
Fixed by https://github.com/entity-neural-network/entity-gym/commit/1953c83ed394206a2578dab930b459f720e6e740
