### ISSUE TITLE
Deprecated action mask in Complex Action Spaces tutorial

### ISSUE THREAD

**Issue by Bene94** [entity-neural-network/entity-gym#18]
The deprecated function is used in the last code box of the tutorial:             

`actions={
                "Move": DenseCategoricalActionMask(
                    actor_types=["Robot"],`

**Comment by Bene94** [comment]
Also:

 `for (_, i), action in zip(move.actors, move.actions):`

Should be:
    `for (_, i), action in zip(move.actors, move.indices):`

**Comment by cswinter** [comment]
fixed by https://github.com/entity-neural-network/entity-gym/commit/03781987f93ee14fbec98086f1a3f32b4a4854ba and https://github.com/entity-neural-network/entity-gym/commit/d3ed57c4bdeed96b6af2bbef320998c663f3c4dc
